# Generated by Django 3.1.7 on 2021-02-25 08:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+25485885632', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
