# Generated by Django 3.1.7 on 2021-02-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
