# Generated by Django 3.1.7 on 2021-02-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210226_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
