# Generated by Django 2.2.13 on 2021-02-24 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('locality', models.CharField(max_length=150)),
                ('estate', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True)),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rental', models.BooleanField(default=True)),
                ('for_sale', models.BooleanField(default=False)),
                ('rental_or_for_sale', models.BooleanField(blank=True, default=False, null=True)),
                ('agreement_terms', models.CharField(max_length=9)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', imagekit.models.fields.ProcessedImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
