# Generated by Django 2.2.13 on 2021-02-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='garage',
            new_name='parking_space',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='agreement_terms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='rental_or_for_sale',
        ),
    ]
