# Generated by Django 3.1.7 on 2021-02-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_bathrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='asking_price',
            new_name='buying_price',
        ),
    ]
