# Generated by Django 2.2.13 on 2021-02-24 08:25

from django.db import migrations, models
import realtors.validators


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.image_restriction]),
        ),
    ]
